# SPDX-License-Identifier: GPL-2.0
CFLAGS += -Wall -O2

all:

TEST_GEN_FILES := private_node_tool

TEST_PROGS := dax-kmem-hotplug.sh \
	      private_node_hotplug.sh \
	      private_node_isolation.sh

include ../lib.mk
